### PR TITLE
Fetch the latest version of a record if it has been modified by afterHooks before returning it

### PR DESCRIPTION
**Pull request by Floriferous**
This is a suggestion for a change that would make `Factory.create` a bit more consistent.

If you modify a new document in your after hooks, it's possible for this package to return you an outdated version of this document. And so instead of returning the old version, if there are any hooks, we refetch and return it instead.

### CODE REVIEW

**Comment by dburles** [comment]
Thanks @Floriferous, that seems reasonable to me. Would you mind adding a couple of sync and async tests?

**Comment by Floriferous** [comment]
Hi there,

How do I run tests in this package? I tried to run this command I found online:

`meteor test-packages ./ --driver-package meteortesting:mocha`

But it starts the test runner without finding any tests and says `0 passing`.

**Comment by dburles** [comment]
Hey close! just run `meteor test-packages ./`

**Comment by Floriferous** [comment]
Here it is, let me know if it's good :)

**Comment by dburles** [comment]
This looks perfect, thanks!

**Pull request merged**
