### PR TITLE
add async functions to work with meteor 2.8+

### PR DESCRIPTION
**Pull request by minhna**
I added tests for new async functions.

### CODE REVIEW

**Comment by dburles** [comment]
Thanks @minhna, looks good. Would be good to avoid duplicating the logic between sync and async functions, it would make the code a bit more complicated, but it would help with maintainability (and avoid the need to duplicate all the tests too).

Would you mind updating the docs? I assume that now in modern Meteor, users would be using the async functions by default?

**Comment by minhna** [comment]
@dburles we need to keep the original sync functions to make it works with meteor 2.8 or older. Those existing tests written in meteor app 2.8- still work as expected.
But when people try to update their app to new async api, they will also migrate their tests. So I think this is the best way.

**Comment by minhna** [comment]
I updated README file.

**Comment by dburles** [comment]
You can still keep the the sync versions but share the inner logic so that isn't duplicated. That's what I meant.

**Comment by dburles** [comment]
Is it possible to use the sync API in Meteor after 2.8? Should it be the default moving forward?

**Comment by minhna** [comment]
Yes, it's possible to use sync API in Meteor 2.8 and 2.9.

**Comment by dburles** [comment]
Thanks @minhna I'll get this released soon

**Comment by dburles** [comment]
Published as 1.3.0.

**Pull request merged**
